# This is a basic workflow to help you get started with Actions
name: Git-tinz # name is Learn
on: # how it executes; manually here
  push:
jobs: 
  test-push:
    runs-on: 
      ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Print index.html
        run: cat index.html
      
  #   needs: trial
  #   steps:
  #     - name: First Push
  #       run: |
  #         echo "Testing push trigger in GA😎"
  #         echo "Xup, ${{ vars.TEST_NAME }}!"
  
  # trial:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Create directories
  #       run: |
  #         mkdir test
  #         cd test     
  #         touch t.txt b.sh     
  #         echo "I'm in $PWD." > b.sh
  #         cat b.sh
  #         echo "I created directories."
  #         ls -la

# jobs:  # job name: test 
#   test:
#     runs-on: ubuntu-latest   # where it is executed; os it runs on
#     # needs: trial # runs after the trial job completes
#     steps:
#       - name: First test
#         run: 
#           echo "Testing GitHub Actions."
#       - name: Multi-line
#         run: |
#           echo "Try other stuff."
#           echo "Testing stuff 🚀🚀🚀"
#           echo "Ran trial prior to this"
#           echo "Now we are talking 🚀🚀🚀"
  # trial:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create directories
  #       run: |
  #         mkdir test
  #         cd test     
  #         touch t.txt b.sh     
  #         echo "I'm in $PWD." > b.sh
  #         cat b.sh
  #         echo "I created directories."
  #         ls -la
        
      
    
