# This is a basic workflow to help you get started with Actions
name: Learn # name is Learn
on: # how it executes; manually here
  workflow_dispatch:
jobs:  # job name: test 
  test:
    runs-on: ubuntu-latest     # where it is executed; os it runs on
    steps:
      - name: First test
        run: 
          echo "Testing GitHub Actions."
      - name: Multi-line
        run: |
          echo "Try other stuff."
          echo "Testing stuff 🚀🚀🚀"
          echo "Now we are talking 🚀🚀🚀"
  trial:
    runs-on: ubuntu-latest
    steps:
      - name: Create directories
        run: |
          mkdir test
          cd test     
          touch t.txt b.sh     
          echo "I'm in $PWD." > b.sh
          cat b.sh
          echo "I created directories."
          ls -la
        
      
    
